name: Clang Format Checker
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v1.0.1
        with:
          sources: "src/**/*.h,src/**/*.cpp,src/**/*.cc"
          style: file
