name: IFPEN el7 gimkl/2018b

on:
  push:
    branches: [ main, dev/cea, dev/ifpen, dev/ci_ifpen ]
  pull_request:
    branches: [ main, dev/cea, dev/ifpen, dev/ci_ifpen ]
  workflow_dispatch:

env:
  # Alien
  ALIEN_BUILD_DIR: /__w/alien/alien/alien_build
  ALIEN_INSTALL_DIR: /__w/alien/alien/alien_install
  ALIEN_SOURCE_DIR: /__w/alien/alien/alien
  # Arccon
  ARCCON_BUILD_DIR: /__w/alien/alien/arccon_build
  ARCCON_INSTALL_DIR: /__w/alien/alien/arccon_install
  ARCCON_SOURCE_DIR: /__w/alien/alien/arccon
  # Arccore
  ARCCORE_BUILD_DIR: /__w/alien/alien/arccore_build
  ARCCORE_INSTALL_DIR: /__w/alien/alien/arccore_install
  ARCCORE_SOURCE_DIR: /__w/alien/alien/arccore
  # CMake
  CM_BUILD_TYPE: Release
  # CTest
  CT_OPTS: "--timeout 300"

jobs:
  arccon-install:
    name: arccon-install
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/arcaneframework/centos-gimkl-2018b-alien:7-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: arcaneframework/framework
          path: ${{ env.ARCCON_SOURCE_DIR }}
          ref: main
      - name: Configure
        shell: bash
        run: |
          source /env.sh
          cmake -S ${{ env.ARCCON_SOURCE_DIR }}/arccon -B ${{ env.ARCCON_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCCON_INSTALL_DIR }}
      - name: Build
        shell: bash
        run: |
          source /env.sh
          cmake --build ${{ env.ARCCON_BUILD_DIR }}
      - name: Install
        shell: bash
        run: |
          source /env.sh
          cmake --install ${{ env.ARCCON_BUILD_DIR }}
      - name: Tar install artifact
        shell: bash
        run: tar cf arccon-install-artifact.tar ${{ env.ARCCON_INSTALL_DIR }}
      - name: Upload install artifact
        uses: actions/upload-artifact@v2
        with:
          name: arccon-install-artifact
          path: arccon-install-artifact.tar
          retention-days: 1

  arccore-install:
    name: arccore-install
    needs:
      - arccon-install
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/arcaneframework/centos-gimkl-2018b-alien:7-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: arcaneframework/framework
          path: ${{ env.ARCCORE_SOURCE_DIR }}
          ref: main
      - name: Download arccon install artifact
        uses: actions/download-artifact@v2
        with:
          name: arccon-install-artifact
      - name: Untar arccon install artifact
        shell: bash
        run: tar xf arccon-install-artifact.tar -C /
      - name: Configure
        shell: bash
        run: |
          source /env.sh
          cmake -S ${{ env.ARCCORE_SOURCE_DIR }}/arccore -B ${{ env.ARCCORE_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ARCCORE_INSTALL_DIR }} -DArccon_DIR=${{ env.ARCCON_INSTALL_DIR }}/share/cmake/Arccon -DBUILD_SHARED_LIBS=ON
      - name: Build
        shell: bash
        run: |
          source /env.sh
          cmake --build ${{ env.ARCCORE_BUILD_DIR }}
      - name: Install
        shell: bash
        run: |
          source /env.sh
          cmake --install ${{ env.ARCCORE_BUILD_DIR }}
      - name: Tar build artifact
        shell: bash
        run: tar cf arccore-build-artifact.tar ${{ env.ARCCORE_BUILD_DIR }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: arccore-build-artifact
          path: arccore-build-artifact.tar
          retention-days: 1
      - name: Tar install artifact
        shell: bash
        run: tar cf arccore-install-artifact.tar ${{ env.ARCCORE_INSTALL_DIR }}
      - name: Upload install artifact
        uses: actions/upload-artifact@v2
        with:
          name: arccore-install-artifact
          path: arccore-install-artifact.tar
          retention-days: 1

  alien-install:
    name: alien-install
    needs:
      - arccon-install
      - arccore-install
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: ghcr.io/arcaneframework/centos-gimkl-2018b-alien:7-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.ALIEN_SOURCE_DIR }}
      - name: Download arccon install artifact
        uses: actions/download-artifact@v2
        with:
          name: arccon-install-artifact
      - name: Untar arccon install artifact
        shell: bash
        run: tar xf arccon-install-artifact.tar -C /
      - name: Download arccore install artifact
        uses: actions/download-artifact@v2
        with:
          name: arccore-install-artifact
      - name: Untar arccore install artifact
        shell: bash
        run: tar xf arccore-install-artifact.tar -C /
      - name: Configure
        shell: bash
        run: |
          source /env.sh
          cmake -S ${{ env.ALIEN_SOURCE_DIR }} -B ${{ env.ALIEN_BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CM_BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.ALIEN_INSTALL_DIR }} -DALIENDEV_EMBEDDED=OFF -DArccon_DIR=${{ env.ARCCON_INSTALL_DIR }}/share/cmake/Arccon -DArccore_DIR=${{ env.ARCCORE_INSTALL_DIR }}/lib/cmake/Arccore -DCMAKE_FIND_DEBUG_MODE=1 -DVerbose=ON -DBoost_NO_BOOST_CMAKE=ON -DBUILD_SHARED_LIBS=ON -DALIEN_USE_HDF5=ON -DCMAKE_CXX_FLAGS="-L${EBROOTLIBXML2} -lxml2"
      - name: Build
        shell: bash
        run: |
          source /env.sh
          cmake --build ${{ env.ALIEN_BUILD_DIR }}
      - name: Install
        shell: bash
        run: |
          source /env.sh
          cmake --install ${{ env.ALIEN_BUILD_DIR }}
      - name: Tar build artifact
        shell: bash
        run: tar cf alien-build-artifact.tar ${{ env.ALIEN_BUILD_DIR }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: alien-build-artifact
          path: alien-build-artifact.tar
          retention-days: 1

  arccore-test:
    name: arccore-test
    needs:
      - arccore-install
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/arcaneframework/centos-gimkl-2018b-alien:7-latest
    strategy:
      fail-fast: false
    steps:
      - name: Download arccore build artifact
        uses: actions/download-artifact@v2
        with:
          name: arccore-build-artifact
      - name: Untar arccore build artifact
        shell: bash
        run: tar xf arccore-build-artifact.tar -C /
      - name: Test
        shell: bash
        run: |
          source /env.sh
          cd ${{ env.ARCCORE_BUILD_DIR }}
          ctest ${{ env.CT_OPTS }}
      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: arccore-test-artifact
          path: ${{ env.ARCCORE_BUILD_DIR }}/Testing
          retention-days: 1

  alien-test:
    name: alien-test
    needs:
      - arccore-install
      - alien-install
    runs-on: ubuntu-latest
    timeout-minutes: 180
    container:
      image: ghcr.io/arcaneframework/centos-gimkl-2018b-alien:7-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.ALIEN_SOURCE_DIR }}
      - name: Download alien build artifact
        uses: actions/download-artifact@v2
        with:
          name: alien-build-artifact
      - name: Untar alien build artifact
        shell: bash
        run: tar xf alien-build-artifact.tar -C /
      - name: Download arccore install artifact
        uses: actions/download-artifact@v2
        with:
          name: arccore-install-artifact
      - name: Untar arccore install artifact
        shell: bash
        run: tar xf arccore-install-artifact.tar -C /
      - name: Test
        shell: bash
        run: |
          source /env.sh
          cd ${{ env.ALIEN_BUILD_DIR }}
          ctest ${{ env.CT_OPTS }}
      - name: Upload test artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: alien-test-artifact
          path: ${{ env.ALIEN_BUILD_DIR }}/Testing
          retention-days: 1
